# Generated by Django 4.2.3 on 2023-07-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliersarea', '0002_servicearea_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='suppliersarea.provider'),
            preserve_default=False,
        ),
    ]
